# Generated by Django 2.1.2 on 2018-10-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180308_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='safe_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='show_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='tag_blacklist',
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
