# Generated by Django 2.1.2 on 2018-10-30 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20181030_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('modify_profile', 'Can change values from all profiles.'),)},
        ),
    ]
