# Generated by Django 2.1.2 on 2018-11-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20181030_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('codename', models.CharField(max_length=100, verbose_name='codename')),
            ],
            options={
                'verbose_name': 'account permission',
                'verbose_name_plural': 'account permissions',
                'ordering': ['codename'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='account_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific account permissions for this user.', related_name='account_perms', related_query_name='user', to='account.AccountPermission', verbose_name='account permissions'),
        ),
    ]
