# Generated by Django 2.1.2 on 2018-11-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('account', '0008_auto_20181101_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountPermission',
            new_name='Privileges',
        ),
        migrations.AlterModelOptions(
            name='privileges',
            options={'ordering': ['codename'], 'verbose_name': 'privilege', 'verbose_name_plural': 'privileges'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_permissions',
        ),
        migrations.AddField(
            model_name='account',
            name='privileges',
            field=models.ManyToManyField(blank=True, help_text='Specific privileges for this user.', related_name='account_privs', related_query_name='user', to='account.Privileges', verbose_name='privileges'),
        ),
    ]
