# Generated by Django 2.1.2 on 2018-11-02 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20181101_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=2500)),
                ('expiration', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='privileges',
        ),
        migrations.AddField(
            model_name='timeout',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeout_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeout',
            name='revoked',
            field=models.ManyToManyField(blank=True, help_text='Privileges revoked from this user.', related_name='revoked_privs', related_query_name='user', to='account.Privileges', verbose_name='privileges'),
        ),
        migrations.AddField(
            model_name='timeout',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_timedout', to=settings.AUTH_USER_MODEL),
        ),
    ]
