sudo: required
language: python
python: 
  - "3.6"
  - "3.7"
env:
  - DJANGO_VERSION=2.1.2
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
script:
  - python manage.py test
