# Generated by Django 2.0 on 2018-02-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0002_auto_20180106_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.IntegerField(null=True),
        ),
    ]
