# Generated by Django 2.0 on 2018-03-01 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('booru', '0004_auto_20180228_1837'), ('booru', '0005_auto_20180228_1840'), ('booru', '0006_auto_20180228_1841'), ('booru', '0007_auto_20180228_1842'), ('booru', '0008_auto_20180228_2205'), ('booru', '0009_auto_20180228_2218')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booru', '0003_post_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Implication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_implications', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_implications', to=settings.AUTH_USER_MODEL)),
                ('from_post', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_implications', to='booru.PostTag')),
                ('to_post', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_implications', to='booru.PostTag')),
            ],
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_aliases', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_aliases', to=settings.AUTH_USER_MODEL)),
                ('from_post', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_aliases', to='booru.PostTag')),
                ('to_post', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_aliases', to='booru.PostTag')),
            ],
        ),
    ]
