# Generated by Django 2.1.2 on 2018-12-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0004_auto_20181118_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttag',
            options={'permissions': (('manage_tags', 'Can manage tags'),), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
