# Generated by Django 2.0 on 2018-03-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0004_auto_20180228_1837_squashed_0009_auto_20180228_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alias',
            options={'verbose_name_plural': 'Aliases'},
        ),
    ]
