# Generated by Django 2.0 on 2018-03-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0005_auto_20180228_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alias',
            old_name='from_post',
            new_name='from_tag',
        ),
        migrations.RenameField(
            model_name='alias',
            old_name='to_post',
            new_name='to_tag',
        ),
        migrations.RenameField(
            model_name='implication',
            old_name='from_post',
            new_name='from_tag',
        ),
        migrations.RenameField(
            model_name='implication',
            old_name='to_post',
            new_name='to_tag',
        ),
    ]
