# Generated by Django 2.0 on 2018-03-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0006_auto_20180304_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alias',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='implication',
            name='approved',
        ),
        migrations.AddField(
            model_name='alias',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Unapproved')], default=0),
        ),
        migrations.AddField(
            model_name='implication',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Unapproved')], default=0),
        ),
    ]
