# Generated by Django 2.1.2 on 2018-12-11 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0006_comment_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalposttag',
            name='update_timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posttag',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
