# Generated by Django 2.1.4 on 2018-12-13 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0007_auto_20181211_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalposttag',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='booru.Category'),
        ),
    ]
