# Generated by Django 2.0 on 2018-03-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0007_auto_20180305_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
