# Generated by Django 2.0 on 2018-03-08 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0007_auto_20180305_2004'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorevote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booru.Post'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booru.Post'),
        ),
        migrations.AlterField(
            model_name='scorevote',
            name='point',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('account', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='scorevote',
            unique_together={('account', 'post')},
        ),
    ]
