# Generated by Django 4.1.5 on 2023-01-26 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('booru', '0008_auto_20181213_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalgallery',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical gallery', 'verbose_name_plural': 'historical Galleries'},
        ),
        migrations.AlterModelOptions(
            name='historicalpost',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical post', 'verbose_name_plural': 'historical posts'},
        ),
        migrations.AlterModelOptions(
            name='historicalposttag',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Tag', 'verbose_name_plural': 'historical Tags'},
        ),
        migrations.AlterField(
            model_name='historicalgallery',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalposttag',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalposttag',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalposttag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='taggedpost',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='taggedpost',
            name='object_id',
            field=models.IntegerField(db_index=True, verbose_name='object ID'),
        ),
        migrations.AlterField(
            model_name='taggedpost',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='booru.posttag'),
        ),
    ]
