# Generated by Django 2.0 on 2018-03-08 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0008_auto_20180306_0352'),
        ('booru', '0008_auto_20180308_0048_squashed_0010_auto_20180308_0109'),
    ]

    operations = [
    ]
