# Generated by Django 2.0 on 2018-03-08 06:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booru', '0008_auto_20180308_0048_squashed_0010_auto_20180308_0109'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scorevote',
            unique_together={('account', 'post')},
        ),
    ]
