# Generated by Django 2.0 on 2018-03-15 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booru', '0009_merge_20180308_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttag',
            name='associated_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='posttag',
            name='associated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posttag',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posttag',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='posttag',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='1990-1-1'),
            preserve_default=False,
        ),
    ]
