# Generated by Django 2.0 on 2018-03-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0010_auto_20180315_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags_mirror',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
