# Generated by Django 2.0 on 2018-03-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0010_pool'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pool',
            new_name='Gallery',
        ),
    ]
