# Generated by Django 2.0 on 2018-04-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0015_auto_20180417_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags_mirror',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
