# Generated by Django 2.1.2 on 2018-10-24 00:19

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('booru', '0017_auto_20181023_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttag',
            name='aliases',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
