# Generated by Django 2.1.2 on 2018-10-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0018_posttag_aliases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('change_status', 'Can change the status of posts'),)},
        ),
    ]
