# Generated by Django 2.1.2 on 2018-10-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0021_auto_20181027_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('change_status', 'Can change the status of posts'), ('mass_rename', 'Can mass rename posts'))},
        ),
    ]
