# Generated by Django 2.1.2 on 2018-10-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0021_auto_20181027_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('change_status', 'Can change the status of posts'), ('mass_rename', 'Can mass rename posts'))},
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
