# Generated by Django 2.1.2 on 2018-10-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0022_auto_20181027_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
