# Generated by Django 2.1.2 on 2018-10-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0025_historicaltagbase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltagbase',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalTagBase',
        ),
    ]
