# Generated by Django 2.1.2 on 2018-10-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0027_historicaltaggedpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltaggedpost',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='historicaltaggedpost',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltaggedpost',
            name='tag',
        ),
        migrations.DeleteModel(
            name='HistoricalTaggedPost',
        ),
    ]
