# Generated by Django 2.1.2 on 2018-10-29 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0028_auto_20181029_1734'),
        ('booru', '0024_gallery'),
    ]

    operations = [
    ]
