# Generated by Django 2.1.2 on 2018-10-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0030_historicalgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='posts_mirror',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='historicalgallery',
            name='posts_mirror',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
