# Generated by Django 2.1.2 on 2018-10-31 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0031_auto_20181030_0015'),
        ('booru', '0022_auto_20181027_2000'),
    ]

    operations = [
    ]
