# Generated by Django 2.1.2 on 2018-10-31 03:44

from django.db import migrations, models


def create_configs(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Configuration = apps.get_model("booru", "Configuration")
    Configuration.objects.using(db_alias).create(code_name="site_title", value="Boorunaut")
    Configuration.objects.using(db_alias).create(code_name="google_analytics_id", value="")

class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0032_merge_20181031_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.RunPython(create_configs),
    ]
