# Generated by Django 2.1.2 on 2018-11-20 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_bannedhash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannedhash',
            options={'permissions': (('ban_hashes', 'Can ban hashes of media'),), 'verbose_name_plural': 'Banned hashes (MD5)'},
        ),
        migrations.AddField(
            model_name='bannedhash',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bannedhash',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannedhash',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
