# Generated by Django 2.1.2 on 2018-11-20 19:43

from django.db import migrations


def create_configs(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Configuration = apps.get_model("booru", "Configuration")
    Configuration.objects.using(db_alias).create(code_name="announcement", value="")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181120_1657'),
    ]

    operations = [
        migrations.RunPython(create_configs),
    ]

