# Generated by Django 2.1.2 on 2018-12-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_postflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='postflag',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Disapproved')], default=0),
        ),
    ]
