# Generated by Django 2.1.2 on 2018-12-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_postflag_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postflag',
            name='reason',
            field=models.CharField(max_length=500),
        ),
    ]
