# Generated by Django 2.1.2 on 2018-12-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181209_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postflag',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Resolved')], default=0),
        ),
    ]
