# Generated by Django 2.0 on 2018-03-05 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booru', '0003_post_parent'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booru.Post'),
        ),
        migrations.AddField(
            model_name='account',
            name='comments_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='email_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=250),
        ),
    ]
