# Generated by Django 2.1.2 on 2018-11-13 21:39

from django.db import migrations


def create_configs(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Privilege = apps.get_model("account", "Privilege")
    Privilege.objects.using(db_alias).create(codename="can_comment", name="User can make a comment")
    Privilege.objects.using(db_alias).create(codename="can_login", name="User can login into the site")

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181113_2121'),
    ]

    operations = [
        migrations.RunPython(create_configs),
    ]
