# Generated by Django 2.1.2 on 2018-11-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181113_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('modify_profile', 'Can change values from all profiles.'), ('change_user_group', 'Can set the group of a user.'), ('ban_user', 'Can ban users.'), ('ban_mod', 'Can ban moderators.'))},
        ),
    ]
