# Generated by Django 2.0 on 2018-03-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='about',
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
