# Generated by Django 2.1.2 on 2018-11-25 00:26

from django.db import migrations


def create_configs(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Group = apps.get_model("auth", "Group")
    admin = Group.objects.using(db_alias).create(name='Administrator')
    mod = Group.objects.using(db_alias).create(name='Moderator')
    janitor = Group.objects.using(db_alias).create(name='Janitor')
    user = Group.objects.using(db_alias).create(name='User')

    Permission = apps.get_model("auth", "Permission")
    modify_profile = Permission.objects.using(db_alias).get(codename='modify_profile')
    ban_user = Permission.objects.using(db_alias).get(codename='ban_user')
    ban_mod = Permission.objects.using(db_alias).get(codename='ban_mod')
    change_configurations = Permission.objects.using(db_alias).get(codename='change_configurations')
    change_status = Permission.objects.using(db_alias).get(codename='change_status')
    mass_rename = Permission.objects.using(db_alias).get(codename='mass_rename')
    ban_hashes = Permission.objects.using(db_alias).get(codename='ban_hashes')
    change_user_group = Permission.objects.using(db_alias).get(codename='change_user_group')    

    admin.permissions.add(modify_profile, ban_user, ban_mod, change_configurations, change_status,
                          mass_rename, ban_hashes, change_user_group)
    mod.permissions.add(modify_profile, ban_user, change_status, mass_rename, ban_hashes)
    janitor.permissions.add(change_status, mass_rename, ban_hashes)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20181130_0232'),
    ]

    operations = [
        migrations.RunPython(create_configs),
    ]
