# Generated by Django 2.1.2 on 2018-11-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20181101_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeout',
            name='expiration',
            field=models.DateTimeField(),
        ),
    ]
