# Generated by Django 2.1.2 on 2018-11-02 01:01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('account', '0011_auto_20181101_2157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Privileges',
            new_name='Privilege',
        ),
    ]
