# Generated by Django 2.1.2 on 2018-11-13 03:22

import booru.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_account_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', booru.managers.UserManager()),
            ],
        ),
    ]
